### ISSUE TITLE
Composer v2 compatibility

### ISSUE THREAD

**Issue by daun** [wireframe-framework/processwire-composer-installer#2]
The installer seems to be incompatible with the new composer version 2.0.

Unfortunately, I'm not familiar enough with the composer plugin api to make a guess at the required changes.

```
wireframe-framework/processwire-composer-installer 1.0.4 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
```

**Comment by teppokoivula** [comment]
Thanks for reporting, @daun! Testing on Composer 2 has been on my todo list — I know they changed some things and was a little worried that it would mean that something is broken.

The issue you're having here is about version constraints. Technically fixing this would be easy (looks like I need to allow `^1.0 || ^2.0`), but I'll have to run some tests first. Hopefully there's a clean way to support both versions of composer-plugin-api, otherwise this could get tricky.

I'll put aside some time for this in the next few days.

**Comment by daun** [comment]
For what it's worth, the upstream `pw-module-installer` has [the same issue](https://github.com/harikt/pwmoduleinstaller/issues/2). A [suggested solution](https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb) seems to take both versions 1 and 2 in account.

**Comment by daun** [comment]
BTW, did you know about the official [composer/installers](https://github.com/composer/installers/) package? It's a single package with user-contributed custom installers for different frameworks. I just created a [PR to add ProcessWire support](https://github.com/composer/installers/pull/472). This should make custom PW installers superfluous and it works with composer v2 🤹‍♂️

**Comment by teppokoivula** [comment]
@daun, I've just released version 1.1.0 of processwire-composer-installer. This should fix the Composer 2.0 issue, though please let me know if you're still experiencing problems!

I'm aware of composer/installers, but as far as I can remember, there were a couple of reasons I didn't go that way initially. My main issue at the moment was that there didn't seem to be a simple way to provide custom install paths, which at least in our case is an essential feature.

In our setup ProcessWire modules are not installed to site/modules/, but rather a custom path — hence the pw-module-path extra argument in the root composer.json file. Admittedly I haven't dug too far into the composer/installers logic, so perhaps there is a way to handle this. If not, this may be another package that I have to somehow bypass 😄

**Comment by teppokoivula** [comment]
@daun, just a quick note on your PR: currently many modules specify pw-module as their type, since that's what Hari's installer originally used, and mainly for backwards compatibility that's also what wireframe-framework/processwire-composer-installer uses.

This seems potentially problematic, to be honest, as it's essentially the third way to install modules via Composer, and also incompatible with existing solutions. It's in line with composer/installers naming conventions, though, and thus may make sense anyway.

I'm honestly a little conflicted about this: I'd like to go all in with composer/installers, but at the moment I see some issues with this approach: losing custom path support would be a major issue for setups like ours, while creating two groups of incompatible module installers would be another.

Mostly just thinking out loud, not really sure what's the best way to approach this yet 🙂

**Comment by daun** [comment]
@teppokoivula The composer installers package has a way to define custom paths that overwrite the installer's standard paths. Not sure if that's what you meant.

```json
    "extra": {
        "installer-paths": {
            "custom/modules/path/{$name}/": ["type:processwire-module"]
        }
    }
```

I agree it's a little confusing to have too many ways to install modules. Then again, I'd prefer to go with the canonical version whenever possible, and the official composer package seems to be as canonical as it gets. The original Hari installer seems to be unmaintained and ProcessWire doesn't officially recommend a composer installer since that's something the module authors have to decide. I see the fact that it now uses a different package type string as a positive since it makes a clear distinction between the original third-party installer and the composer one.

**Comment by daun** [comment]
Thanks for the patch release!

**Comment by teppokoivula** [comment]
You're right, of course — I was literally just reading the same thing. Looks like the path thing may not be an issue. Which is awesome :)

**Comment by daun** [comment]
As for the site profiles, the PR could be extended to add support for those as well ☃️

**Comment by teppokoivula** [comment]
I wouldn't worry too much about site profiles, though perhaps that's something to consider. These are a little trickier, I believe, or at least I had to go through a few extra hoops to get them working. Also: I don't have numbers, but my guess is that it's not a very popular feature; I originally envisioned folks going all in with Composer and installing everything with it, but so far I've seen little evidence of anyone (except me) installing profiles this way 😉

> I agree it's a little confusing to have too many ways to install modules. Then again, I'd prefer to go with the canonical version whenever possible, and the official composer package seems to be as canonical as it gets.

Agreed.

> The original Hari installer seems to be unmaintained and ProcessWire doesn't officially recommend a composer installer since that's something the module authors have to decide. I see the fact that it now uses a different package type string as a positive since it makes a clear distinction between the original third-party installer and the composer one.

Assuming that the PR gets merged, I'm going to give the official installer a try in our environment, and if all goes well I'm likely going to add a note to this package recommending module authors to use that one instead. Might also be a good idea to ask if Ryan would be open to officially recommending it.

Anyway, thanks for bringing this up — both the Composer 2 compatibility issue in this installer, as well as the official installers repository! Seems like we're moving to a good direction 🙂

**Comment by daun** [comment]
> Assuming that the PR gets merged, I'm going to give the official installer a try in our environment, and if all goes well I'm likely going to add a note to this package recommending module authors to use that one instead. Might also be a good idea to ask if Ryan would be open to officially recommending it.

Sounds great 🐦 Let me know if the installer implementation needs more work.

> Seems like we're moving to a good direction

🎷

**Comment by daun** [comment]
Just a quick note that the PR was merged and [a new release](https://github.com/composer/installers/releases/tag/v1.10.0) tagged for the official composer/installers package. Just tried it out with one of my PW modules and it's working as expected.

**Comment by teppokoivula** [comment]
Thanks, @daun! I'll give that a try soon(ish) :)
